version: '3.8'
services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    container_name: product-service
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    environment:
      - PORT=3001
      - MONGO_URI=mongodb://mongodb:27017/products_db

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    container_name: order-service
    restart: always
    ports:
      - "3002:3002"
    depends_on:
      - mongodb
    environment:
      - PORT=3002
      - MONGO_URI=mongodb://mongodb:27017/orders_db


  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - product-service
      - order-service
      - redis
    environment:
      - GATEWAY_PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379

volumes:
  mongo_data:
